server:
  port: 8082

spring:
  application:
    name: cloudE-ucenter-provider
  cloud:
    config:
      uri: http://localhost:8888
      profile: @profiles.active@
      name: cloud-config

#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  typeAliasesPackage: com.cloudE.mapper

eureka:
  instance:
    prefer-ip-address: true

ucTask:
  dynamicParameter: 1